### ISSUE TITLE
Test database

### ISSUE THREAD

**Issue by cjx3711** [cjx3711/pm25tracker#4]
Related to #3 
Possible database crashes.

**Comment by cjx3711** [comment]
App crashed after refactoring the menu items.

```
03-08 13:06:31.980 15142-15142/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.chaijiaxun.pm25tracker, PID: 15142
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chaijiaxun.pm25tracker/com.chaijiaxun.pm25tracker.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.activeandroid.TableInfo.getTableName()' on a null object reference
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2726)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2787)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6247)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.activeandroid.TableInfo.getTableName()' on a null object reference
                                                       at com.activeandroid.Cache.getTableName(Cache.java:156)
                                                       at com.activeandroid.query.From.addFrom(From.java:169)
                                                       at com.activeandroid.query.From.toSql(From.java:250)
                                                       at com.activeandroid.query.From.execute(From.java:298)
                                                       at com.chaijiaxun.pm25tracker.database.SensorReading.getList(SensorReading.java:44)
                                                       at com.chaijiaxun.pm25tracker.MainActivity.loadReadings(MainActivity.java:208)
                                                       at com.chaijiaxun.pm25tracker.MainActivity.onCreate(MainActivity.java:84)
                                                       at android.app.Activity.performCreate(Activity.java:6754)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2787) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6247) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
```
